#!/usr/bin/env tcsh
#
# Copyright (c) 2011 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $Id: run-some-m2pa-tests,v 1.3 2011/03/20 04:12:33 tuexen Exp $
#

set timeout = 10
set sleeptime = 1
set testcases = (m2pa-algn-v-01 \
                 m2pa-algn-v-02 \
                 m2pa-algn-v-03 \
                 m2pa-algn-v-04 \
                 m2pa-algn-v-05 \
                 m2pa-algn-v-06 \
                 m2pa-algn-v-07 \
                 m2pa-algn-i-01 \
                 m2pa-algn-i-02 \
                 m2pa-algn-i-03 \
                 m2pa-algn-i-04 \
                 m2pa-algn-i-05 \
                 m2pa-algn-o-01 \
                 m2pa-algn-o-02 \
                 m2pa-algn-o-03 \
                 m2pa-algn-o-04 \
                 m2pa-algn-o-05 \
                 m2pa-sctp-v-01 \
                 m2pa-sctp-v-02 \
                 m2pa-sctp-v-03 \
                 m2pa-sctp-v-04 \
                 m2pa-sctp-v-05 \
                 m2pa-sctp-v-06 \
                 m2pa-sctp-v-07 \
                 m2pa-msg-v-01  \
                 m2pa-msg-v-02  \
                 m2pa-msg-v-03  \
                 m2pa-msg-v-04  \
                 m2pa-msg-v-05  \
                 m2pa-msg-v-06  \
                 m2pa-msg-v-07  \
                 m2pa-msg-v-08  \
                 m2pa-msg-v-09  \
                 m2pa-msg-v-10  \
                 m2pa-msg-v-11  \
                 m2pa-msg-v-12  \
                 m2pa-msg-v-13  \
                 m2pa-msg-i-01  \
                 m2pa-msg-i-02  \
                 m2pa-msg-i-03  \
                 m2pa-msg-i-04  )

foreach testcase ($testcases)
  (run-m2pa-test -t $timeout $testcase > /dev/tty) >& /dev/null
  sleep $sleeptime
end
